package ${package}.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Oct 25 15:50:37 CEST 2016]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class TurbineRolePermission
    extends ${package}.om.BaseTurbineRolePermission implements org.apache.fulcrum.security.torque.peer.TurbineRolePermissionPeerMapper
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;




}
