package ${package}.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Jan 12 15:33:37 CET 2018]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class TurbineUserGroupRole
    extends ${package}.om.BaseTurbineUserGroupRole
    implements org.apache.fulcrum.security.torque.peer.TurbineUserGroupRoleModelPeerMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1515767617070L;



}
