package ${package}.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Nov 25 16:49:55 CET 2013]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class TurbinePermissionPeerImpl
    extends ${package}.om.BaseTurbinePermissionPeerImpl implements org.apache.fulcrum.security.torque.peer.TorqueTurbinePeer<TurbinePermission>
{
    /** Serial version */
    private static final long serialVersionUID = 138394595924L;

}
