package ${package}.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Sep 04 12:20:05 CEST 2014]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class TurbinePermissionPeer
    extends ${package}.om.BaseTurbinePermissionPeer implements org.apache.fulcrum.security.torque.peer.Peer
{

}
